CREATE TABLE IF NOT EXISTS `APPS` (
	`app_name` VARCHAR(255) NOT NULL UNIQUE,
	`reviews` INTEGER NOT NULL,
	`size` INTEGER NOT NULL,
	`installs` INTEGER NOT NULL,
	`price` FLOAT NOT NULL,
	`content` VARCHAR(255) NOT NULL,
	`last updated` DATETIME NOT NULL,
	`app_id` VARCHAR(255) NOT NULL,
	`type` VARCHAR(255),
	`category` VARCHAR(255),
	`rating` VARCHAR(255),
	PRIMARY KEY(`app_id`)
);


CREATE TABLE IF NOT EXISTS `categories` (
	`category_id` INTEGER NOT NULL UNIQUE,
	`category` VARCHAR(255),
	`genre` VARCHAR(255),
	PRIMARY KEY(`category_id`)
);


CREATE TABLE IF NOT EXISTS `types` (
	`type_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Type` VARCHAR(255),
	PRIMARY KEY(`type_id`)
);


CREATE TABLE IF NOT EXISTS `genres` (
	`genres_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`genre` VARCHAR(255),
	PRIMARY KEY(`genres_id`)
);


CREATE TABLE IF NOT EXISTS `content_ratings` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`rating` VARCHAR(255),
	PRIMARY KEY(`id`)
);


ALTER TABLE `categories`
ADD FOREIGN KEY(`category`) REFERENCES `APPS`(`category`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `content_ratings`
ADD FOREIGN KEY(`rating`) REFERENCES `APPS`(`rating`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `types`
ADD FOREIGN KEY(`Type`) REFERENCES `APPS`(`type`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `categories`
ADD FOREIGN KEY(`genre`) REFERENCES `genres`(`genre`)
ON UPDATE NO ACTION ON DELETE NO ACTION;